name: build-and-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build and Run Tests
        run: mvn package
      - name: Publish coverage reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET }}
